name: Lint
on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main']
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt flake8 black
      - run: flake8 app.py
      - run: black --check app.py
