name: UI Tests
on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main']
jobs:
  UI-Tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        browser: [firefox, chromium]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - run: pip install -r requirements.txt pytest playwright pytest-playwright "huggingface_hub[cli]"
      - run: huggingface-cli download jncraton/Llama-3.2-3B-Instruct-ct2-int8 --revision 5da4ba8
      - run: python -m playwright install ${{ matrix.browser }}
      - run: pytest --durations=5 --browser ${{ matrix.browser }}
